/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.conrad;

import java.io.BufferedReader;

public class Application {
    public static void main(String[] args) {
    }

    public String parseAccountNumbers(BufferedReader inputReader) {
        return null;
    }
}
